
"use client";

import { FormEvent, useState } from "react";

type RecommendationResult = {
  status?: string;
  message?: string;
  alerts?: string[];
  recommendations?: string[];
  [key: string]: unknown;
};

export default function RecommendationPage() {
  const [formData, setFormData] = useState({
    recommended_crop: "Rice",
    crop_confidence: "85",
    detected_disease: "Tomato___healthy",
    disease_confidence: "95",
    predicted_yield: "2.2",
  });

  const [result, setResult] =
    useState<RecommendationResult | null>(null);

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleChange = (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    const { name, value } = event.target;

    setFormData((previous) => ({
      ...previous,
      [name]: value,
    }));

    setResult(null);
    setError("");
  };

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const response = await fetch("/api/recommendation", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          recommended_crop: formData.recommended_crop,
          crop_confidence: Number(formData.crop_confidence),
          detected_disease: formData.detected_disease,
          disease_confidence: Number(
            formData.disease_confidence
          ),
          predicted_yield: Number(formData.predicted_yield),
        }),
      });

      const responseText = await response.text();

      let data: RecommendationResult;

      try {
        data = JSON.parse(responseText);
      } catch {
        throw new Error(
          responseText || "Invalid response received from server."
        );
      }

      if (!response.ok) {
        throw new Error(
          data.message || "Failed to generate agricultural recommendation."
        );
      }

      setResult(data);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Failed to generate agricultural recommendation."
      );
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setFormData({
      recommended_crop: "Rice",
      crop_confidence: "85",
      detected_disease: "Tomato___healthy",
      disease_confidence: "95",
      predicted_yield: "2.2",
    });

    setResult(null);
    setError("");
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-green-50 via-white to-emerald-50 px-4 py-8 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-5xl">
        {/* HEADER */}

        <header className="mb-10 flex items-start gap-5">
          <div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-3xl bg-green-800 text-2xl font-black text-white shadow-xl shadow-green-900/20">
            SA
          </div>

          <div>
            <h1 className="text-3xl font-black tracking-tight text-green-900 sm:text-5xl">
              Agricultural Recommendation
            </h1>

            <p className="mt-3 text-sm leading-6 text-gray-500 sm:text-base">
              Combine AI predictions to generate meaningful
              agricultural insights.
            </p>
          </div>
        </header>

        {/* MAIN CARD */}

        <section className="rounded-3xl border border-white/70 bg-white/90 p-6 shadow-2xl shadow-green-900/10 backdrop-blur-xl md:p-9">
          {/* FORM HEADER */}

          <div className="mb-8 flex items-start gap-4">
            <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-green-100 text-sm font-black text-green-700">
              01
            </div>

            <div>
              <h2 className="text-xl font-black text-gray-900 sm:text-2xl">
                AI Prediction Inputs
              </h2>

              <p className="mt-1 text-sm leading-6 text-gray-400">
                Enter the outputs generated by the agriculture AI
                modules.
              </p>
            </div>
          </div>

          <form onSubmit={handleSubmit}>
            <div className="grid gap-6 md:grid-cols-2">
              {/* RECOMMENDED CROP */}

              <InputField
                label="Recommended Crop"
                name="recommended_crop"
                value={formData.recommended_crop}
                onChange={handleChange}
                placeholder="Rice"
                type="text"
              />

              {/* CROP CONFIDENCE */}

              <InputField
                label="Crop Confidence"
                name="crop_confidence"
                value={formData.crop_confidence}
                onChange={handleChange}
                placeholder="85"
                type="number"
                unit="%"
                min="0"
                max="100"
                step="0.01"
              />

              {/* DETECTED DISEASE */}

              <InputField
                label="Detected Disease"
                name="detected_disease"
                value={formData.detected_disease}
                onChange={handleChange}
                placeholder="Tomato___healthy"
                type="text"
              />

              {/* DISEASE CONFIDENCE */}

              <InputField
                label="Disease Confidence"
                name="disease_confidence"
                value={formData.disease_confidence}
                onChange={handleChange}
                placeholder="95"
                type="number"
                unit="%"
                min="0"
                max="100"
                step="0.01"
              />

              {/* PREDICTED YIELD */}

              <div className="md:col-span-2">
                <InputField
                  label="Predicted Yield"
                  name="predicted_yield"
                  value={formData.predicted_yield}
                  onChange={handleChange}
                  placeholder="2.2"
                  type="number"
                  unit="t/ha"
                  min="0"
                  step="0.001"
                />
              </div>
            </div>

            {/* SUBMIT BUTTON */}

            <button
              type="submit"
              disabled={loading}
              className="mt-8 flex w-full items-center justify-center gap-3 rounded-2xl bg-green-800 px-6 py-4 text-sm font-black text-white shadow-xl shadow-green-900/20 transition hover:bg-green-900 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {loading ? (
                <>
                  <span className="button-spinner" />
                  Generating Recommendation...
                </>
              ) : (
                <>
                  Generate Recommendation
                  <ArrowIcon />
                </>
              )}
            </button>
          </form>

          {/* ERROR */}

          {error && (
            <div className="mt-6 flex items-start gap-3 rounded-2xl border border-red-200 bg-red-50 p-4">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-red-100 font-black text-red-600">
                !
              </div>

              <div>
                <p className="font-black text-red-800">
                  Recommendation Failed
                </p>

                <p className="mt-1 text-sm leading-6 text-red-700">
                  {error}
                </p>
              </div>
            </div>
          )}

          {/* RESULT */}

          {result && (
            <section className="mt-8 rounded-3xl border border-green-100 bg-green-50/70 p-6">
              <div className="flex items-center gap-3">
                <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-green-100 text-green-700">
                  <CheckIcon />
                </div>

                <div>
                  <p className="text-xs font-black uppercase tracking-wider text-green-700">
                    02 • AI Result
                  </p>

                  <h2 className="mt-1 text-2xl font-black text-gray-900">
                    Agricultural Insights
                  </h2>
                </div>
              </div>

              {/* STATUS */}

              {result.status && (
                <div className="mt-6 rounded-2xl border border-green-200 bg-white p-4">
                  <p className="text-xs font-black uppercase tracking-wider text-gray-400">
                    Recommendation Status
                  </p>

                  <p className="mt-2 text-lg font-black capitalize text-green-800">
                    {result.status.replaceAll("_", " ")}
                  </p>
                </div>
              )}

              {/* ALERTS */}

              {Array.isArray(result.alerts) &&
                result.alerts.length > 0 && (
                  <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-5">
                    <h3 className="font-black text-red-800">
                      Alerts
                    </h3>

                    <ul className="mt-3 space-y-2">
                      {result.alerts.map((alert, index) => (
                        <li
                          key={index}
                          className="text-sm leading-6 text-red-700"
                        >
                          {alert}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

              {/* RECOMMENDATIONS */}

              {Array.isArray(result.recommendations) &&
                result.recommendations.length > 0 && (
                  <div className="mt-5 rounded-2xl border border-green-200 bg-white p-5">
                    <h3 className="font-black text-green-800">
                      Recommendations
                    </h3>

                    <ul className="mt-3 space-y-3">
                      {result.recommendations.map(
                        (recommendation, index) => (
                          <li
                            key={index}
                            className="flex items-start gap-3 text-sm leading-6 text-gray-700"
                          >
                            <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-green-600" />
                            {recommendation}
                          </li>
                        )
                      )}
                    </ul>
                  </div>
                )}

              {/* COMPLETE RESPONSE */}

              <div className="mt-5 rounded-2xl border border-gray-200 bg-white p-5">
                <h3 className="font-black text-gray-900">
                  Complete AI Response
                </h3>

                <pre className="mt-4 overflow-x-auto whitespace-pre-wrap break-words rounded-xl bg-gray-950 p-4 text-xs leading-6 text-green-300">
                  {JSON.stringify(result, null, 2)}
                </pre>
              </div>

              {/* RESET */}

              <button
                type="button"
                onClick={resetForm}
                className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl border border-gray-200 bg-white px-6 py-3.5 text-sm font-black text-gray-700 transition hover:border-green-300 hover:bg-green-50 hover:text-green-800"
              >
                <RefreshIcon />
                Make Another Recommendation
              </button>
            </section>
          )}
        </section>

        {/* FOOTER */}

        <footer className="py-8 text-center">
          <p className="text-xs leading-6 text-gray-400">
            Smart Agriculture AI combines model outputs to provide
            decision-support information. Recommendations should be
            interpreted together with local agricultural conditions.
          </p>
        </footer>
      </div>
    </main>
  );
}

/* =========================================================
   INPUT FIELD
========================================================= */

function InputField({
  label,
  name,
  value,
  onChange,
  placeholder,
  type,
  unit,
  min,
  max,
  step,
}: {
  label: string;
  name: string;
  value: string;
  onChange: (
    event: React.ChangeEvent<HTMLInputElement>
  ) => void;
  placeholder?: string;
  type: string;
  unit?: string;
  min?: string;
  max?: string;
  step?: string;
}) {
  return (
    <div>
      <label
        htmlFor={name}
        className="mb-2 block text-xs font-black uppercase tracking-wider text-gray-500"
      >
        {label}
      </label>

      <div className="relative">
        <input
          id={name}
          name={name}
          value={value}
          onChange={onChange}
          placeholder={placeholder}
          type={type}
          min={min}
          max={max}
          step={step}
          required
          className={`w-full rounded-2xl border border-gray-200 bg-gray-50/80 px-4 py-3.5 text-sm font-semibold text-gray-900 outline-none transition focus:border-green-500 focus:bg-white focus:ring-4 focus:ring-green-100 ${
            unit ? "pr-20" : ""
          }`}
        />

        {unit && (
          <span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 rounded-lg bg-white px-2 py-1 text-xs font-black text-gray-500 shadow-sm">
            {unit}
          </span>
        )}
      </div>
    </div>
  );
}

/* =========================================================
   ICONS
========================================================= */

function ArrowIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      className="h-5 w-5"
    >
      <path d="M5 12h14" />
      <path d="m13 6 6 6-6 6" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      className="h-5 w-5"
    >
      <path d="m5 12 4 4L19 6" />
    </svg>
  );
}

function RefreshIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      className="h-4 w-4"
    >
      <path d="M20 11a8 8 0 0 0-14.8-4L4 9" />
      <path d="M4 5v4h4" />
      <path d="M4 13a8 8 0 0 0 14.8 4L20 15" />
      <path d="M20 19v-4h-4" />
    </svg>
  );
}