"use client";

import { useState } from "react";

type RecommendationResult = {
  recommended_crop: string;
  crop_confidence: number;
  predicted_disease: string | null;
  disease_confidence: number | null;
  predicted_yield: number | null;
  overall_status: string;
  alerts: string[];
  recommendations: string[];
};

export default function RecommendationPage() {
  const [formData, setFormData] = useState({
    recommended_crop: "Rice",
    crop_confidence: "85",
    predicted_disease: "Tomato___healthy",
    disease_confidence: "95",
    predicted_yield: "2.2",
  });

  const [result, setResult] =
    useState<RecommendationResult | null>(null);

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement>
  ) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const response = await fetch(
        "http://localhost:5000/api/recommendation",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            recommended_crop: formData.recommended_crop,
            crop_confidence: Number(formData.crop_confidence),
            predicted_disease:
              formData.predicted_disease || null,
            disease_confidence:
              formData.disease_confidence
                ? Number(formData.disease_confidence)
                : null,
            predicted_yield:
              formData.predicted_yield
                ? Number(formData.predicted_yield)
                : null,
          }),
        }
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.message || "Recommendation failed"
        );
      }

      setResult(data);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Something went wrong"
      );
    } finally {
      setLoading(false);
    }
  };

  const cleanDiseaseName = (name: string | null) => {
    if (!name) return "Not available";

    return name
      .replace(/___/g, " - ")
      .replace(/_/g, " ");
  };

  return (
    <main className="page">

      <div className="glow glowOne"></div>
      <div className="glow glowTwo"></div>

      <section className="container">

        {/* Header */}

        <header className="header">

          <div className="logo">
            🌾
          </div>

          <div>
            <div className="eyebrow">
              SMART AGRICULTURE AI
            </div>

            <h1>
              Agricultural Recommendation
            </h1>

            <p>
              Combine AI predictions to generate
              meaningful agricultural insights.
            </p>
          </div>

        </header>


        {/* Main Card */}

        <section className="card">

          <div className="sectionHeader">

            <div className="number">
              01
            </div>

            <div>
              <h2>
                AI Prediction Inputs
              </h2>

              <p>
                Enter the outputs generated by the
                agriculture AI modules.
              </p>
            </div>

          </div>


          <form onSubmit={handleSubmit}>

            <div className="grid">

              {/* Crop */}

              <div className="field">

                <label>
                  Recommended Crop
                </label>

                <input
                  name="recommended_crop"
                  value={formData.recommended_crop}
                  onChange={handleChange}
                  placeholder="e.g. Rice"
                  required
                />

              </div>


              {/* Crop Confidence */}

              <div className="field">

                <label>
                  Crop Confidence
                </label>

                <div className="inputUnit">

                  <input
                    name="crop_confidence"
                    type="number"
                    min="0"
                    max="100"
                    step="0.01"
                    value={formData.crop_confidence}
                    onChange={handleChange}
                    required
                  />

                  <span>%</span>

                </div>

              </div>


              {/* Disease */}

              <div className="field">

                <label>
                  Detected Disease
                </label>

                <input
                  name="predicted_disease"
                  value={formData.predicted_disease}
                  onChange={handleChange}
                  placeholder="e.g. Tomato___healthy"
                />

              </div>


              {/* Disease Confidence */}

              <div className="field">

                <label>
                  Disease Confidence
                </label>

                <div className="inputUnit">

                  <input
                    name="disease_confidence"
                    type="number"
                    min="0"
                    max="100"
                    step="0.01"
                    value={formData.disease_confidence}
                    onChange={handleChange}
                  />

                  <span>%</span>

                </div>

              </div>


              {/* Yield */}

              <div className="field full">

                <label>
                  Predicted Yield
                </label>

                <div className="inputUnit">

                  <input
                    name="predicted_yield"
                    type="number"
                    min="0"
                    step="0.0001"
                    value={formData.predicted_yield}
                    onChange={handleChange}
                  />

                  <span>t/ha</span>

                </div>

              </div>

            </div>


            {/* Button */}

            <button
              className="button"
              type="submit"
              disabled={loading}
            >

              {loading ? (
                <>
                  <span className="spinner"></span>
                  Generating...
                </>
              ) : (
                <>
                  ✦ Generate Recommendation
                  <span>→</span>
                </>
              )}

            </button>

          </form>


          {/* Error */}

          {error && (

            <div className="error">

              <span>⚠️</span>

              <div>
                <strong>
                  Recommendation failed
                </strong>

                <p>
                  {error}
                </p>
              </div>

            </div>

          )}


          {/* Result */}

          {result && (

            <section className="result">

              <div className="resultTop">

                <div>

                  <div className="resultEyebrow">
                    AI ANALYSIS COMPLETE
                  </div>

                  <h2>
                    Agricultural Insights
                  </h2>

                </div>

                <div
                  className={
                    result.overall_status ===
                    "normal"
                      ? "status normal"
                      : "status warning"
                  }
                >
                  {result.overall_status ===
                  "normal"
                    ? "✓ Normal"
                    : "⚠ Attention"}
                </div>

              </div>


              {/* Summary */}

              <div className="summary">

                <div className="summaryCard">

                  <span className="summaryIcon">
                    🌾
                  </span>

                  <div>

                    <small>
                      RECOMMENDED CROP
                    </small>

                    <strong>
                      {result.recommended_crop}
                    </strong>

                    <span>
                      {result.crop_confidence}%
                      confidence
                    </span>

                  </div>

                </div>


                <div className="summaryCard">

                  <span className="summaryIcon">
                    🦠
                  </span>

                  <div>

                    <small>
                      PLANT CONDITION
                    </small>

                    <strong>
                      {cleanDiseaseName(
                        result.predicted_disease
                      )}
                    </strong>

                    {result.disease_confidence !==
                      null && (
                      <span>
                        {result.disease_confidence}%
                        confidence
                      </span>
                    )}

                  </div>

                </div>


                <div className="summaryCard">

                  <span className="summaryIcon">
                    📊
                  </span>

                  <div>

                    <small>
                      PREDICTED YIELD
                    </small>

                    <strong>
                      {result.predicted_yield ??
                        "N/A"}
                    </strong>

                    {result.predicted_yield !==
                      null && (
                      <span>
                        Tonnes/Hectare
                      </span>
                    )}

                  </div>

                </div>

              </div>


              {/* Alerts */}

              {result.alerts.length > 0 && (

                <div className="insightBlock alertBlock">

                  <h3>
                    ⚠️ Attention
                  </h3>

                  {result.alerts.map(
                    (alert, index) => (
                      <div
                        className="insight"
                        key={index}
                      >
                        <span>•</span>
                        <p>{alert}</p>
                      </div>
                    )
                  )}

                </div>

              )}


              {/* Recommendations */}

              {result.recommendations.length >
                0 && (

                <div className="insightBlock">

                  <h3>
                    💡 Recommendations
                  </h3>

                  {result.recommendations.map(
                    (recommendation, index) => (
                      <div
                        className="insight"
                        key={index}
                      >
                        <span>✓</span>
                        <p>
                          {recommendation}
                        </p>
                      </div>
                    )
                  )}

                </div>

              )}

            </section>

          )}

        </section>


        <footer>
          🤖 Powered by Smart Agriculture AI
        </footer>

      </section>


      <style jsx>{`

        * {
          box-sizing: border-box;
        }

        .page {
          min-height: 100vh;
          padding: 55px 20px;
          position: relative;
          overflow: hidden;
          background:
            linear-gradient(
              135deg,
              #f0fdf4,
              #f8fafc 50%,
              #ecfdf5
            );
          color: #17221b;
        }

        .glow {
          position: absolute;
          width: 420px;
          height: 420px;
          border-radius: 50%;
          filter: blur(110px);
          opacity: .25;
          pointer-events: none;
        }

        .glowOne {
          top: -200px;
          left: -160px;
          background: #4ade80;
        }

        .glowTwo {
          right: -180px;
          bottom: -180px;
          background: #86efac;
        }

        .container {
          width: 100%;
          max-width: 950px;
          margin: auto;
          position: relative;
          z-index: 1;
        }

        .header {
          display: flex;
          align-items: center;
          gap: 20px;
          margin-bottom: 30px;
        }

        .logo {
          width: 70px;
          height: 70px;
          display: flex;
          align-items: center;
          justify-content: center;
          border-radius: 20px;
          background: #166534;
          font-size: 34px;
          box-shadow:
            0 12px 30px
            rgba(22,101,52,.2);
        }

        .eyebrow,
        .resultEyebrow {
          font-size: 11px;
          font-weight: 800;
          letter-spacing: 2px;
          color: #15803d;
        }

        .eyebrow {
          margin-bottom: 5px;
        }

        h1 {
          margin: 0;
          font-size: 36px;
          letter-spacing: -1px;
          color: #14532d;
        }

        .header p {
          margin: 7px 0 0;
          color: #64748b;
          font-size: 14px;
        }

        .card {
          padding: 35px;
          border-radius: 24px;
          background: rgba(255,255,255,.93);
          box-shadow:
            0 20px 60px
            rgba(15,23,42,.08);
          border: 1px solid
            rgba(255,255,255,.8);
        }

        .sectionHeader {
          display: flex;
          align-items: center;
          gap: 14px;
          margin-bottom: 28px;
        }

        .number {
          width: 42px;
          height: 42px;
          border-radius: 12px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: #dcfce7;
          color: #166534;
          font-size: 12px;
          font-weight: 800;
        }

        .sectionHeader h2 {
          margin: 0;
          font-size: 20px;
          color: #1e293b;
        }

        .sectionHeader p {
          margin: 4px 0 0;
          font-size: 13px;
          color: #94a3b8;
        }

        .grid {
          display: grid;
          grid-template-columns:
            repeat(2, 1fr);
          gap: 22px;
        }

        .field {
          display: flex;
          flex-direction: column;
        }

        .field.full {
          grid-column: 1 / -1;
        }

        label {
          margin-bottom: 8px;
          font-size: 13px;
          font-weight: 700;
          color: #334155;
        }

        input {
          width: 100%;
          height: 48px;
          border: 1px solid #dbe3df;
          border-radius: 10px;
          background: white;
          padding: 0 14px;
          outline: none;
          font-size: 14px;
          color: #1e293b;
          transition: .2s;
        }

        input:focus {
          border-color: #22c55e;
          box-shadow:
            0 0 0 3px
            rgba(34,197,94,.12);
        }

        .inputUnit {
          position: relative;
        }

        .inputUnit input {
          padding-right: 65px;
        }

        .inputUnit span {
          position: absolute;
          right: 14px;
          top: 50%;
          transform: translateY(-50%);
          font-size: 12px;
          font-weight: 700;
          color: #64748b;
        }

        .button {
          width: 100%;
          height: 54px;
          margin-top: 30px;
          border: none;
          border-radius: 12px;
          background: #166534;
          color: white;
          font-size: 15px;
          font-weight: 700;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 10px;
          box-shadow:
            0 8px 20px
            rgba(22,101,52,.18);
          transition: .2s;
        }

        .button:hover:not(:disabled) {
          background: #14532d;
          transform: translateY(-1px);
        }

        .button:disabled {
          opacity: .7;
          cursor: not-allowed;
        }

        .spinner {
          width: 17px;
          height: 17px;
          border: 2px solid
            rgba(255,255,255,.3);
          border-top-color: white;
          border-radius: 50%;
          animation: spin .7s linear infinite;
        }

        @keyframes spin {
          to {
            transform: rotate(360deg);
          }
        }

        .error {
          margin-top: 25px;
          padding: 16px;
          border-radius: 12px;
          display: flex;
          gap: 12px;
          background: #fef2f2;
          border: 1px solid #fecaca;
          color: #991b1b;
        }

        .error strong {
          font-size: 14px;
        }

        .error p {
          margin: 4px 0 0;
          font-size: 13px;
        }

        .result {
          margin-top: 32px;
          padding: 28px;
          border-radius: 18px;
          background:
            linear-gradient(
              135deg,
              #f0fdf4,
              #dcfce7
            );
          border: 1px solid #bbf7d0;
        }

        .resultTop {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 20px;
        }

        .result h2 {
          margin: 5px 0 0;
          color: #14532d;
          font-size: 22px;
        }

        .status {
          padding: 8px 13px;
          border-radius: 999px;
          font-size: 12px;
          font-weight: 800;
        }

        .normal {
          background: #dcfce7;
          color: #166534;
        }

        .warning {
          background: #fef3c7;
          color: #92400e;
        }

        .summary {
          display: grid;
          grid-template-columns:
            repeat(3, 1fr);
          gap: 14px;
          margin-top: 25px;
        }

        .summaryCard {
          padding: 17px;
          border-radius: 13px;
          background: rgba(255,255,255,.75);
          display: flex;
          gap: 12px;
          align-items: flex-start;
        }

        .summaryIcon {
          font-size: 23px;
        }

        .summaryCard div {
          display: flex;
          flex-direction: column;
        }

        .summaryCard small {
          font-size: 9px;
          font-weight: 800;
          letter-spacing: 1px;
          color: #64748b;
        }

        .summaryCard strong {
          margin-top: 5px;
          font-size: 15px;
          color: #14532d;
        }

        .summaryCard span:last-child {
          margin-top: 3px;
          font-size: 11px;
          color: #64748b;
        }

        .insightBlock {
          margin-top: 22px;
          padding: 18px;
          border-radius: 13px;
          background: rgba(255,255,255,.7);
        }

        .alertBlock {
          background: #fffbeb;
          border: 1px solid #fde68a;
        }

        .insightBlock h3 {
          margin: 0 0 12px;
          font-size: 14px;
          color: #334155;
        }

        .insight {
          display: flex;
          gap: 10px;
          margin-top: 10px;
        }

        .insight span {
          font-weight: 800;
          color: #16a34a;
        }

        .insight p {
          margin: 0;
          font-size: 13px;
          line-height: 1.6;
          color: #475569;
        }

        footer {
          margin-top: 24px;
          text-align: center;
          color: #94a3b8;
          font-size: 12px;
        }

        @media (max-width: 700px) {

          .page {
            padding: 30px 15px;
          }

          .header {
            align-items: flex-start;
          }

          h1 {
            font-size: 27px;
          }

          .logo {
            width: 55px;
            height: 55px;
            font-size: 27px;
          }

          .card {
            padding: 22px;
          }

          .grid,
          .summary {
            grid-template-columns: 1fr;
          }

          .field.full {
            grid-column: auto;
          }

          .resultTop {
            align-items: flex-start;
            flex-direction: column;
          }

        }

      `}</style>

    </main>
  );
}